In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("../data/moodcare_knowledge.csv")

In [10]:
df.head()

,id,category,user_state,advice,activity_type
0,1,loneliness,feeling alone even when surrounded by people,Feeling lonely can happen even when others are...,social_connection
1,2,loneliness,missing someone close,Missing someone is a natural feeling. You can ...,emotional_expression
2,3,loneliness,having no one to talk to,"When you feel like you have no one to talk to,...",social_support
3,4,loneliness,feeling disconnected from others,Feeling disconnected does not mean you are alo...,social_connection
4,5,loneliness,feeling lonely at night,Nighttime loneliness can feel stronger because...,self_care

In [11]:
df.shape

(400, 5)

In [12]:
df.columns

Index(['id', 'category', 'user_state', 'advice', 'activity_type'], dtype='str')

In [14]:
df.isnull().sum()

id               0
category         0
user_state       0
advice           0
activity_type    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df['category'].value_counts()

category
loneliness    50
sadness       50
stress        50
anxiety       50
boredom       50
motivation    50
anger         50
happiness     50
Name: count, dtype: int64

In [18]:
df['user_state'] = df['user_state'].str.strip()
df['advice'] = df['advice'].str.strip()
df['category'] = df['category'].str.lower()

In [20]:
df

,id,category,user_state,advice,activity_type
0,1,loneliness,feeling alone even when surrounded by people,Feeling lonely can happen even when others are...,social_connection
1,2,loneliness,missing someone close,Missing someone is a natural feeling. You can ...,emotional_expression
2,3,loneliness,having no one to talk to,"When you feel like you have no one to talk to,...",social_support
3,4,loneliness,feeling disconnected from others,Feeling disconnected does not mean you are alo...,social_connection
4,5,loneliness,feeling lonely at night,Nighttime loneliness can feel stronger because...,self_care
...,...,...,...,...,...
395,396,happiness,feeling optimistic after a difficult period,Difficult periods can lead to personal growth....,hope_building
396,397,happiness,feeling happy because of helping someone achie...,Supporting others can create fulfillment. Cont...,kindness
397,398,happiness,feeling positive about personal abilities,Believing in yourself supports growth. Continu...,confidence_building
398,399,happiness,feeling calm and emotionally balanced,Emotional balance is valuable. Maintain habits...,mindfulness
399,400,happiness,feeling happy and wanting to maintain positivity,Positive emotions can be strengthened through ...,positive_lifestyle

In [21]:
df.shape

(400, 5)